name: English Language Update Request
description: English Language Glossary Update Request Definition
title: "[English Update]: GlossaryWordHere"
labels: ["english"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request an update to the glossary!
  - type: textarea
    id: details
    attributes:
      label: Details (optional)
      description: Please feel free to add any additional details here
      placeholder: Tell us what you see!
      value: "Optional details"
    validations:
      required: false
